CREATE TABLE IF NOT EXISTS `vision_runs` (
  `SourceLine` varchar(40) NOT NULL,
  `RunId` int(11) NOT NULL,
  `StartTime` datetime NOT NULL,
  `EndTime` datetime DEFAULT NULL,
  `FirstTime` datetime DEFAULT NULL,
  `LastTime` datetime DEFAULT NULL,
  `ProductId` varchar(40) NOT NULL,
  `nDetected` int(11) DEFAULT '0',
  `nPassed` int(11) DEFAULT '0',
  `nMarginal` int(11) DEFAULT '0',
  `nRejected` int(11) DEFAULT '0',
  `WidthAverage` double DEFAULT NULL, `WidthFirst` double DEFAULT NULL, `WidthLast` double DEFAULT NULL, `WidthMin` double DEFAULT NULL, `WidthMax` double DEFAULT NULL,
  `HeightAverage` double DEFAULT NULL, `HeightFirst` double DEFAULT NULL, `HeightLast` double DEFAULT NULL, `HeightMin` double DEFAULT NULL, `HeightMax` double DEFAULT NULL,
  `DMajorAverage` double DEFAULT NULL, `DMajorFirst` double DEFAULT NULL, `DMajorLast` double DEFAULT NULL, `DMajorMin` double DEFAULT NULL, `DMajorMax` double DEFAULT NULL,
  `DMinorAverage` double DEFAULT NULL, `DMinorFirst` double DEFAULT NULL, `DMinorLast` double DEFAULT NULL, `DMinorMin` double DEFAULT NULL, `DMinorMax` double DEFAULT NULL,
  `DAvgAverage` double DEFAULT NULL, `DAvgFirst` double DEFAULT NULL, `DAvgLast` double DEFAULT NULL, `DAvgMin` double DEFAULT NULL, `DAvgMax` double DEFAULT NULL,
  `EFAverage` double DEFAULT NULL, `EFFirst` int(11) DEFAULT NULL, `EFLast` int(11) DEFAULT NULL, `EFMin` int(11) DEFAULT NULL, `EFMax` int(11) DEFAULT NULL,
  `EDAverage` double DEFAULT NULL, `EDFirst` int(11) DEFAULT NULL, `EDLast` int(11) DEFAULT NULL, `EDMin` int(11) DEFAULT NULL, `EDMax` int(11) DEFAULT NULL,
  `HAAverage` double DEFAULT NULL, `HAFirst` double DEFAULT NULL, `HALast` double DEFAULT NULL, `HAMin` double DEFAULT NULL, `HAMax` double DEFAULT NULL,
  `ShapeAverage` double DEFAULT NULL, `ShapeFirst` double DEFAULT NULL, `ShapeLast` double DEFAULT NULL, `ShapeMin` double DEFAULT NULL, `ShapeMax` double DEFAULT NULL,
  `ToastAverage` double DEFAULT NULL, `ToastFirst` int(11) DEFAULT NULL, `ToastLast` int(11) DEFAULT NULL, `ToastMin` int(11) DEFAULT NULL, `ToastMax` int(11) DEFAULT NULL,
  `RawAverage` double DEFAULT NULL, `RawFirst` int(11) DEFAULT NULL, `RawLast` int(11) DEFAULT NULL, `RawMin` int(11) DEFAULT NULL, `RawMax` int(11) DEFAULT NULL,
  `TransAverage` double DEFAULT NULL, `TransFirst` int(11) DEFAULT NULL, `TransLast` int(11) DEFAULT NULL, `TransMin` int(11) DEFAULT NULL, `TransMax` int(11) DEFAULT NULL,
  `LanePosAverage` double DEFAULT NULL, `LanePosFirst` double DEFAULT NULL, `LanePosLast` double DEFAULT NULL, `LanePosMin` double DEFAULT NULL, `LanePosMax` double DEFAULT NULL,
  `nDMajorMin` int(11) DEFAULT '0', `nDMajorMax` int(11) DEFAULT '0',
  `nDMinorMin` int(11) DEFAULT '0', `nDMinorMax` int(11) DEFAULT '0',
  `nDAvgMin` int(11) DEFAULT '0', `nDAvgMax` int(11) DEFAULT '0',
  `nEFMax` int(11) DEFAULT '0', `nEDMax` int(11) DEFAULT '0',
  `nHAMax` int(11) DEFAULT '0', `nShapeMax` int(11) DEFAULT '0',
  `nRawMax` int(11) DEFAULT '0', `nTransMax` int(11) DEFAULT '0',
  `nLaneMin` int(11) DEFAULT '0', `nLaneMax` int(11) DEFAULT '0',
  `SyncUp` datetime DEFAULT NULL,
  `LastUpdate` datetime DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SourceLine`, `RunId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `vision_lanes` (
  `SourceLine` varchar(40) NOT NULL,
  `RunId` int(11) NOT NULL,
  `LaneId` char(1) NOT NULL,
  `FirstTime` datetime DEFAULT NULL,
  `LastTime` datetime DEFAULT NULL,
  `nDetected` int(11) DEFAULT '0',
  `nPassed` int(11) DEFAULT '0',
  `nMarginal` int(11) DEFAULT '0',
  `nRejected` int(11) DEFAULT '0',
  `WidthAverage` double DEFAULT NULL, `WidthFirst` double DEFAULT NULL, `WidthLast` double DEFAULT NULL, `WidthMin` double DEFAULT NULL, `WidthMax` double DEFAULT NULL,
  `HeightAverage` double DEFAULT NULL, `HeightFirst` double DEFAULT NULL, `HeightLast` double DEFAULT NULL, `HeightMin` double DEFAULT NULL, `HeightMax` double DEFAULT NULL,
  `DMajorAverage` double DEFAULT NULL, `DMajorFirst` double DEFAULT NULL, `DMajorLast` double DEFAULT NULL, `DMajorMin` double DEFAULT NULL, `DMajorMax` double DEFAULT NULL,
  `DMinorAverage` double DEFAULT NULL, `DMinorFirst` double DEFAULT NULL, `DMinorLast` double DEFAULT NULL, `DMinorMin` double DEFAULT NULL, `DMinorMax` double DEFAULT NULL,
  `DAvgAverage` double DEFAULT NULL, `DAvgFirst` double DEFAULT NULL, `DAvgLast` double DEFAULT NULL, `DAvgMin` double DEFAULT NULL, `DAvgMax` double DEFAULT NULL,
  `EFAverage` double DEFAULT NULL, `EFFirst` int(11) DEFAULT NULL, `EFLast` int(11) DEFAULT NULL, `EFMin` int(11) DEFAULT NULL, `EFMax` int(11) DEFAULT NULL,
  `EDAverage` double DEFAULT NULL, `EDFirst` int(11) DEFAULT NULL, `EDLast` int(11) DEFAULT NULL, `EDMin` int(11) DEFAULT NULL, `EDMax` int(11) DEFAULT NULL,
  `HAAverage` double DEFAULT NULL, `HAFirst` double DEFAULT NULL, `HALast` double DEFAULT NULL, `HAMin` double DEFAULT NULL, `HAMax` double DEFAULT NULL,
  `ShapeAverage` double DEFAULT NULL, `ShapeFirst` double DEFAULT NULL, `ShapeLast` double DEFAULT NULL, `ShapeMin` double DEFAULT NULL, `ShapeMax` double DEFAULT NULL,
  `ToastAverage` double DEFAULT NULL, `ToastFirst` int(11) DEFAULT NULL, `ToastLast` int(11) DEFAULT NULL, `ToastMin` int(11) DEFAULT NULL, `ToastMax` int(11) DEFAULT NULL,
  `RawAverage` double DEFAULT NULL, `RawFirst` int(11) DEFAULT NULL, `RawLast` int(11) DEFAULT NULL, `RawMin` int(11) DEFAULT NULL, `RawMax` int(11) DEFAULT NULL,
  `TransAverage` double DEFAULT NULL, `TransFirst` int(11) DEFAULT NULL, `TransLast` int(11) DEFAULT NULL, `TransMin` int(11) DEFAULT NULL, `TransMax` int(11) DEFAULT NULL,
  `LanePosAverage` double DEFAULT NULL, `LanePosFirst` double DEFAULT NULL, `LanePosLast` double DEFAULT NULL, `LanePosMin` double DEFAULT NULL, `LanePosMax` double DEFAULT NULL,
  `nDMajorMin` int(11) DEFAULT '0', `nDMajorMax` int(11) DEFAULT '0',
  `nDMinorMin` int(11) DEFAULT '0', `nDMinorMax` int(11) DEFAULT '0',
  `nDAvgMin` int(11) DEFAULT '0', `nDAvgMax` int(11) DEFAULT '0',
  `nEFMax` int(11) DEFAULT '0', `nEDMax` int(11) DEFAULT '0',
  `nHAMax` int(11) DEFAULT '0', `nShapeMax` int(11) DEFAULT '0',
  `nRawMax` int(11) DEFAULT '0', `nTransMax` int(11) DEFAULT '0',
  `nLaneMin` int(11) DEFAULT '0', `nLaneMax` int(11) DEFAULT '0',
  `SyncUp` datetime DEFAULT NULL,
  `LastUpdate` datetime DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SourceLine`, `RunId`, `LaneId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `vision_samples` (
  `SourceLine` varchar(40) NOT NULL,
  `RunId` int(11) NOT NULL,
  `LaneId` char(1) NOT NULL DEFAULT '*',
  `SampNo` bigint(20) NOT NULL,
  `SampTime` datetime NOT NULL,
  `nDetected` int(11) DEFAULT '0',
  `nPassed` int(11) DEFAULT '0',
  `nMarginal` int(11) DEFAULT '0',
  `nRejected` int(11) DEFAULT '0',
  `WidthAverage` double DEFAULT NULL, `WidthFirst` double DEFAULT NULL, `WidthLast` double DEFAULT NULL, `WidthMin` double DEFAULT NULL, `WidthMax` double DEFAULT NULL,
  `HeightAverage` double DEFAULT NULL, `HeightFirst` double DEFAULT NULL, `HeightLast` double DEFAULT NULL, `HeightMin` double DEFAULT NULL, `HeightMax` double DEFAULT NULL,
  `DMajorAverage` double DEFAULT NULL, `DMajorFirst` double DEFAULT NULL, `DMajorLast` double DEFAULT NULL, `DMajorMin` double DEFAULT NULL, `DMajorMax` double DEFAULT NULL,
  `DMinorAverage` double DEFAULT NULL, `DMinorFirst` double DEFAULT NULL, `DMinorLast` double DEFAULT NULL, `DMinorMin` double DEFAULT NULL, `DMinorMax` double DEFAULT NULL,
  `DAvgAverage` double DEFAULT NULL, `DAvgFirst` double DEFAULT NULL, `DAvgLast` double DEFAULT NULL, `DAvgMin` double DEFAULT NULL, `DAvgMax` double DEFAULT NULL,
  `EFAverage` double DEFAULT NULL, `EFFirst` int(11) DEFAULT NULL, `EFLast` int(11) DEFAULT NULL, `EFMin` int(11) DEFAULT NULL, `EFMax` int(11) DEFAULT NULL,
  `EDAverage` double DEFAULT NULL, `EDFirst` int(11) DEFAULT NULL, `EDLast` int(11) DEFAULT NULL, `EDMin` int(11) DEFAULT NULL, `EDMax` int(11) DEFAULT NULL,
  `HAAverage` double DEFAULT NULL, `HAFirst` double DEFAULT NULL, `HALast` double DEFAULT NULL, `HAMin` double DEFAULT NULL, `HAMax` double DEFAULT NULL,
  `ShapeAverage` double DEFAULT NULL, `ShapeFirst` double DEFAULT NULL, `ShapeLast` double DEFAULT NULL, `ShapeMin` double DEFAULT NULL, `ShapeMax` double DEFAULT NULL,
  `ToastAverage` double DEFAULT NULL, `ToastFirst` int(11) DEFAULT NULL, `ToastLast` int(11) DEFAULT NULL, `ToastMin` int(11) DEFAULT NULL, `ToastMax` int(11) DEFAULT NULL,
  `RawAverage` double DEFAULT NULL, `RawFirst` int(11) DEFAULT NULL, `RawLast` int(11) DEFAULT NULL, `RawMin` int(11) DEFAULT NULL, `RawMax` int(11) DEFAULT NULL,
  `TransAverage` double DEFAULT NULL, `TransFirst` int(11) DEFAULT NULL, `TransLast` int(11) DEFAULT NULL, `TransMin` int(11) DEFAULT NULL, `TransMax` int(11) DEFAULT NULL,
  `LanePosAverage` double DEFAULT NULL, `LanePosFirst` double DEFAULT NULL, `LanePosLast` double DEFAULT NULL, `LanePosMin` double DEFAULT NULL, `LanePosMax` double DEFAULT NULL,
  `nDMajorMin` int(11) DEFAULT '0', `nDMajorMax` int(11) DEFAULT '0',
  `nDMinorMin` int(11) DEFAULT '0', `nDMinorMax` int(11) DEFAULT '0',
  `nDAvgMin` int(11) DEFAULT '0', `nDAvgMax` int(11) DEFAULT '0',
  `nEFMax` int(11) DEFAULT '0', `nEDMax` int(11) DEFAULT '0',
  `nHAMax` int(11) DEFAULT '0', `nShapeMax` int(11) DEFAULT '0',
  `nRawMax` int(11) DEFAULT '0', `nTransMax` int(11) DEFAULT '0',
  `nLaneMin` int(11) DEFAULT '0', `nLaneMax` int(11) DEFAULT '0',
  `SyncUp` datetime DEFAULT NULL,
  `LastUpdate` datetime DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SourceLine`, `RunId`, `LaneId`, `SampNo`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `vision_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `SourceLine` varchar(40) NOT NULL,
  `RunId` int(11) NOT NULL,
  `Kind` varchar(20) DEFAULT NULL,
  `Date_Run` datetime NOT NULL,
  `Date_Source` datetime DEFAULT NULL,
  `nDetected` int(11) DEFAULT '0',
  `nPassed` int(11) DEFAULT '0',
  `nMarginal` int(11) DEFAULT '0',
  `nRejected` int(11) DEFAULT '0',
  `Process_Time` double DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `idx_line_date` (`SourceLine`, `Date_Run`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
